### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Tasfa** [lintao199/Image_Dither_Binarization#1]
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    a=sum(s)/12
TypeError: 'int' object is not iterable

**Comment by lintao199** [comment]
```
for i in range(img_height):
    for j in range(img_width):
        s=img.getpixel((j,i))
        a=sum(s)/12
        if(a<bayer[i%7][j&7]):
            img.putpixel((j,i),0)

        else:
            img.putpixel((j,i),(255,255,255))
```
s是图片中某个点的RGB像素，结构是一个长度为3的数组  例如：[255,255,255] 
a=sum(s)/12，目的是将RGB像素  求和然后散列到[0,64]的区间
